# Generated by Django 3.1.1 on 2020-09-09 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('peso', models.FloatField()),
                ('imc', models.FloatField()),
                ('pct_grasa_total', models.FloatField()),
                ('pct_agua', models.FloatField()),
                ('musculo_corporal', models.FloatField()),
                ('calificacion', models.FloatField()),
                ('masa_osea', models.FloatField()),
                ('tasa_metabolismo', models.FloatField()),
                ('edad_metabolica', models.FloatField()),
                ('grasa_visceral', models.FloatField()),
                ('masa_magra_bi', models.FloatField()),
                ('masa_magra_bd', models.FloatField()),
                ('masa_magra_pi', models.FloatField()),
                ('masa_magra_pd', models.FloatField()),
                ('masa_magra_tronco', models.FloatField()),
                ('grasa_segmental_bi', models.FloatField()),
                ('grasa_segmental_bd', models.FloatField()),
                ('grasa_segmental_pi', models.FloatField()),
                ('grasa_segmental_pd', models.FloatField()),
                ('grasa_segmental_tronco', models.FloatField()),
            ],
        ),
    ]
